name: Publish
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Emacs
        uses: purcell/setup-emacs@v6.0
        with:
          version: "29.4"
      - name: Build the website
        run: ./build.sh
